# Generated by Django 3.2.6 on 2021-08-21 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='texto de preguntas')),
            ],
        ),
        migrations.CreateModel(
            name='ElguirRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correcta', models.BooleanField(default=False, verbose_name='Es esta la correcta')),
                ('texto', models.TextField(verbose_name='Texto de la respuesta')),
                ('preguntas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='JUEGO_PREGUNTAS.pregunta')),
            ],
        ),
    ]
