# Generated by Django 3.2.6 on 2021-08-23 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JUEGO_PREGUNTAS', '0002_preguntasrespondidas_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizusuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='puntaje_total')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JUEGO_PREGUNTAS.quizusuario'),
        ),
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
