# Generated by Django 3.2.6 on 2021-08-24 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JUEGO_PREGUNTAS', '0004_rename_usuario_preguntasrespondidas_quizuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='max_puntaje',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=6, verbose_name='Maximo puntaje'),
        ),
        migrations.AlterField(
            model_name='elguirrespuesta',
            name='preguntas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='JUEGO_PREGUNTAS.pregunta'),
        ),
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='quizuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='JUEGO_PREGUNTAS.quizusuario'),
        ),
    ]
