# Generated by Django 3.2.6 on 2021-08-24 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JUEGO_PREGUNTAS', '0006_alter_preguntasrespondidas_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='respuesta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JUEGO_PREGUNTAS.elguirrespuesta'),
        ),
    ]
